SQL> select address.address_id, country, province, city, street, house_number, fax_number, students.phone_number, student_name from address join students on address.address_id=students.address_id;

ADDRESS_ID COUNTRY              PROVINCE                  CITY                 STREET               HOUSE_NUMBER FAX_NUMBER PHONE_NUMBER STUDENT_NAME                                                                                                                                                                                                                                                           
---------- -------------------- ------------------------- -------------------- -------------------- ------------ ---------- ------------ -------------------------                                                                                                                                                                                                                                              
       102 nepal                gandaki                   pokhara              lakeside                       23       2222   9813278725 sandip gajurel                                                                                                                                                                                                                                                         
       103 nepal                gandaki                   myagdi               nayabasti                      11       1111   9813277775 santosh gajurel                                                                                                                                                                                                                                                        
       104 nepal                bagmati                   kathmandu            kotesor                        12       3333   9813277888 shyam nepal                                                                                                                                                                                                                                                            
       105 pakistan             mp                        lahore               karachi                        18       3434   9813277899 hari thapa                                                                                                                                                                                                                                                             
       106 india                mp                        delhi                bandhra                        20       5555   9813277778 ram tamang                                                                                                                                                                                                                                                             
       101 india                utterpradesh              bihar                nagpur                        200       2001   9813277755 sita ghaley                                                                                                                                                                                                                                                            
       100 nepal                bagmati                   kathmandu            jadibuti                       20       2002   9813277735 ram shah                                                                                                                                                                                                                                                               

7 rows selected.

SQL> spool off
