SQL> select course_name, course_leader from leader
  2    join course using(course_code)
  3    join relation using(course_code)
  4    join teacher using (teacher_id);

COURSE_NAME          COURSE_LEADER                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
-------------------- -------------------------                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
bit                  bishwo lama                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
bit                  bishwo lama                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
bit                  bishwo lama                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
bit                  bishwo lama                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
bba                  amrit ghaley                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
bba                  amrit ghaley                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
bbs                  bibek tamang                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

7 rows selected.

SQL> spool off;
